### ISSUE TITLE
Suggestion: rename "Quantile 0.XX" to "pXX"

### ISSUE THREAD

**Issue by jotak** [kiali/k-charted#39]
For shorter and more concise legends:

- Quantile 0.50 => p50
- Quantile 0.95 => p95
etc
Note that "Quantile 0.999" would be p99.9

**Comment by jotak** [comment]
This is how it's displayed in Istio's grafana dashboards: https://istio.io/blog/2017/0.1-announcement/istio_grafana_dashboard-new.png

**Comment by jshaughn** [comment]
+1, pXX is better.

**Comment by abonas** [comment]
+1
