### ISSUE TITLE
Perf comparison pf3 / pf4

### ISSUE THREAD

**Issue by jotak** [kiali/k-charted#45]
Do some comparison between PF impls, especially memory footprint (potential leak in pf3 ?)
Check if it's still needed to hide dashboards when page is not visible in pf4 (that was a workaround for pf3)

**Comment by jotak** [comment]
After a first series of tests, I find similar figures between pf3 and pf4.
For about 30min of monitoring:
- pf3 has [avg: 56MB, min: 49MB, max: 63MB]
- pf4 has [avg: 51MB, min: 37MB, max: 65MB]

I'll monitor for a longer time period later.

**Comment by josejulio** [comment]
Is this related to https://issues.jboss.org/browse/KIALI-3164 ?

> After a first series of tests, I find similar figures between pf3 and pf4.
> For about 30min of monitoring:
> 
> * pf3 has [avg: 56MB, min: 49MB, max: 63MB]
> * pf4 has [avg: 51MB, min: 37MB, max: 65MB]
> 
> I'll monitor for a longer time period later.

Did you try when the they were in the background?

**Comment by jotak** [comment]
We can relate to it, yes, although I wanted to run these comparisons even without the memory leak that was reported.
My hope would be to find a memory leak in pf3 implementation that I wouldn't have in the pf4 one.

**Comment by jotak** [comment]
A longer run (over 3 hours) still gave similar figures, without any evidence of memory leak:

- pf3 has [avg: 45MB, min: 38MB, max: 50MB]
- pf4 has [avg: 50MB, min: 47MB, max: 58MB]

I'm closing this ticket, no obvious gain or loss in memory consumption.

**Comment by josejulio** [comment]
> A longer run (over 3 hours) still gave similar figures, without any evidence of memory leak:
> 
> * pf3 has [avg: 45MB, min: 38MB, max: 50MB], stable over time
> * pf4 has [avg: 50MB, min: 47MB, max: 58MB], stable over time
> 
> I'm closing this ticket, no obvious gain or loss in memory consumption.

How was the test scenario? Did you refresh the data every some seconds? IIRC the bug only happened when refreshing data in the background.

**Comment by jotak** [comment]
Yes, I kept the default refresh (so every 15s), switched to another metrics tabs, enabled some labels, scrolled down&up, then let it untouched for the rest of the run.

**Comment by jotak** [comment]
PS: i'll continue to investigate potential memory leak via https://github.com/kiali/kiali/issues/1279

**Comment by jotak** [comment]
It turns out there is really a memory leak with the charts in PF3 as described in the other ticket.
So it makes the move to PF4 more necessary.
